site_name: Simple Search Engine
site_description: A search engine implementation using Elasticsearch and RAG techniques
site_author: Your Name

repo_name: simple-search-engine
repo_url: https://github.com/yourusername/simple-search-engine

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - User Guide:
    - guides/installation.md
    - guides/quickstart.md
    - guides/configuration.md
  - API Reference:
    - api/core.md
    - api/elastic.md
    - api/models.md
    - api/rag.md
    - api/utils.md
    - api/web.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true 